---
- name: My Handler lab
  hosts: client

  tasks:
    - name: install httpd
      yum: name=httpd state=present

    - name: change port
      lineinfile: path=/etc/httpd/conf/httpd.conf regexp="Listen 80" line="Listen 81"
      notify:
        - restart httpd

    - name: start the service
      service: name=httpd state=started enabled=yes

  handlers:
    - name: restart httpd
      service: name=httpd state=restarted enabled=yes
